sudo: required
services: 
  - docker

before_install:
  - docker build -t peetg/docker-react -f Dockerfile.dev .

script:
  - docker run peetg/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "Docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-559169917305"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"